// This file was generated by Prisma, and assumes you have installed the following:

// npm install --save-dev prisma dotenv

/// <reference types="node" />

import dotenv from "dotenv";

import { defineConfig } from "prisma/config";

dotenv.config({ override: true });

const schemaUrl = process.env["DATABASE_URL"] || process.env["DIRECT_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    url: schemaUrl,
  },
});
